kakasite/kakas/urls.py
from django.urls import path

from . import views

app_name='kakas'
urlpatterns = [ 
    path('', views.IndexView.as_view(), name='index'),
    path('about', views.AboutView.as_view(), name='about'),
    path('contact', views.ContactView.as_view(), name='contact'),
    path('downloads', views.DownloadView.as_view(), name='downloads'),
]

kakasite/kakasite/urls.py
from django.contrib import admin
from django.urls import include, path
from kakas import views

app_name='kakas'
urlpatterns = [
    path('', include('pwa.urls')),
    path('kaka-quest/', include('kakas.urls')),
    path('admin/', admin.site.urls),
]

kakasite/kakas/models.py
from django.db import models

# Create your models here.

kakasite/kakas/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.utils.datastructures import MultiValueDictKeyError
from django.template import loader
from django.urls import reverse
from django.views import View

# Create your views here.

class IndexView(View):
	
    template_name = 'kakas/index.html'

    def get(self, request, *args, **kwargs):
        title = "Kaka Conservation"
        return render(request, self.template_name, {'title': title})

class AboutView(View):
	
    template_name = 'kakas/about.html'

    def get(self, request, *args, **kwargs):
        title = "About Us"
        return render(request, self.template_name, {'title': title})

class ContactView(View):
	
    template_name = 'kakas/contact.html'

    def get(self, request, *args, **kwargs):
        title = "About Us"
        return render(request, self.template_name, {'title': title})

class DownloadView(View):
	
    template_name = 'kakas/downloads.html'

    def get(self, request, *args, **kwargs):
        title = "About Us"
        return render(request, self.template_name, {'title': title})

kakasite/kakas/templates/kakas/about.html
{% extends "./base.html" %}

{% block content %}
    <p>Once extinct in the Otago area, kākās have been brought back home by the efforts of researchers and conservationists at Orokonui Ecosanctuary. The
        world has changed in many ways since they were last here, and so now they need your help to avoid going extinct once again.
    </p>
{% endblock content %}

kakasite/kakas/templates/kakas/base.html
{% load sass_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ title }}</title>
    {% load pwa %}
    {% progressive_web_app_meta %}
    <link rel="stylesheet" type="text/css" href="{% sass_src 'demo.sass' %}" />
</head>
<body>
    {% include "./navigation.html" %}
        <div class="wrapper">
            {% block content %}
            {% endblock content %}
        </div>
        <div class="push"></div>
    {% include "./footer.html" %}
</body>
</html>

kakasite/kakas/templates/kakas/contact.html
{% extends "./base.html" %}

{% block content %}
    <p>Contact us at: don't contact us.</p>
{% endblock content %}

kakasite/kakas/templates/kakas/downloads.html
{% extends "./base.html" %}
{% load static %}
{% block content %}
<div class="panel">
    <img src="{% static 'img/kaka-1.jpg' %}" />
    <p class="img-caption">Here's a picture of a kākā you can have.</p>
</div>

<div class="panel">
<img src="{% static 'img/kaka-family.jpg' %}" />
<p class="img-caption">These are two kākās being jolly birdos.</p>
</div>
{% endblock content %}

kakasite/kakas/templates/kakas/footer.html
<div class="footer-container">
    <div class="footer-bar">
        <p>&copy; The Kaka Quest Squad (name pending) 2019 </p>
    </div>
</div>

kakasite/kakas/templates/kakas/index.html
{% extends "./base.html" %}
{% load static %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
{% block content %}
<div class="panel">
        <img src="{% static 'img/kaka-game.png' %}" style="cursor:pointer" id="game-panel" />
        <div id="prompt"></div>
        <div class="choice-block">
            <div class="choice hidden" id="choice1">Choice 1</div>
            <div class="choice hidden" id="choice2">Choice 2</div>
            <div class="choice hidden" id="choice3">Choice 3</div>
            <div class="choice hidden" id="choice1">Choice 4</div>
            <div class="choice hidden restart" id="restart">Try again!</div>
            <div class="choice hidden youwin" id="restart"><strong>You win!</strong></div>
            <div class="choice hidden restart" id="learn-more">Learn more about you can help protect kākā.</div>
        </div>
    </div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    const base_path = "{% static 'img/kaka-gameX' %}";

    const src_json = "{% static 'data/pages.json' %}";

    let pages;
    
    $.getJSON(src_json, (data) => {
        pages = data["pages"];
    }).done(() => {
        let gameStarted = false;
        $("#game-panel").mousedown(() => {
            if (!gameStarted) {
                gameStarted = true;
                populateFromJson("1a");
            }
        });
        $("#restart").mousedown(() => {
            window.location.replace("{% url 'kakas:index' %}")
            $(".restart").addClass("hidden");
        });
        $("#learn-more").mousedown(() => {
            window.location.replace("{% url 'kakas:about' %}")
            $(".restart").addClass("hidden");
        });

    const populateFromJson = (jsonObjectID) => {
        let jsonObject = pages[jsonObjectID]
        let imgsrc = base_path.replace('X', jsonObjectID + jsonObject["ex"]);
        populate(imgsrc, jsonObject["prompt"], jsonObject["choices"], jsonObject["choice-ids"], jsonObjectID);
    }

    const populate = (imgsrc, prompt, choices, choice_ids, id) => {
        let $prompt = $("#prompt");
        $("#game-panel").attr("src", imgsrc);
        $prompt.text(prompt);
        (prompt) ? $prompt.removeClass("hidden") : $prompt.addClass("hidden");
        for (let i = 0; i < 4; i++)
        {
            let $choicebox = $("#choice" + (i + 1));
            $choicebox.addClass("hidden");
        }
        if (choices) {
            for (let i = 0; i < choices.length; i++)
            {
                let $choicebox = $("#choice" + (i + 1));
                $choicebox.removeClass("hidden");
                $choicebox.text(choices[i]);
                if (choice_ids) {
                    $choicebox.mousedown(() => {
                        populateFromJson(choice_ids[i].toString());
                    });
                }
            }
            $(".restart").addClass("hidden");
        } else {
            if (id == "10b") {
            $("#learn-more").addClass("youwin");
            $(".youwin").removeClass("hidden");
            } else {
            $(".restart").removeClass("hidden");
            }
        }
    }
});
</script>

{% endblock content %}

kakasite/kakas/templates/kakas/navigation.html
<div class="nav-container">
    <div class="arrow-down"></div>
    <div class="navbar">
        <a href="{% url 'kakas:index' %}">Home</a>
        <a href="{% url 'kakas:about' %}">Our Mission</a>
        <a href="{% url 'kakas:contact' %}">Contact Us</a>
        <a href="{% url 'kakas:downloads' %}">Downloads</a>
    </div>
</div>